### PR TITLE
Edit development location

### LINKED ISSUE #143: User cannot edit development location in Edit session
"Drag map to set location" works fine for Create Development, but is not available in an Edit session.  Some developments are in the wrong place, and users will want to adjust the location of existing records. However, we don't want them to do it inadvertently by pushing the map around while in an Edit session.

### PR DESCRIPTION
**Pull request by iangmhill**
Resolves #143 (mostly). This PR extends location editing to the development edit panel, however, as #143 suggested, this iteration does not include a safeguard to prevent a user from accidentally moving the location. A user would have to "cancel" their edits to undo an accidental location nudge.

### CODE REVIEW

File: ember/app/components/mapbox-map.js [hunk 1]
```diff
@@ -325,9 +332,10 @@ export default class extends Component {
   jumpTo(mapService) {
     const dev = mapService.get('viewing');
     if (dev) {
-      const coordinates = [dev.get('longitude') - .00125, dev.get('latitude')];
-      const bounds = new mapboxgl.LngLatBounds([coordinates, coordinates]);
-      this.mapboxglMap.fitBounds(bounds, { padding: 40, maxZoom: 18 });
+      // const coordinates = [dev.get('longitude') - .00125, dev.get('latitude')];
+      // const bounds = new mapboxgl.LngLatBounds([coordinates, coordinates]);
```
Comment (ericyoungberg) [inline ember/app/components/mapbox-map.js]: I'd delete the commented out code that was replaced by something else.
